build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
releases:
  latest:
    release:
      channel: stable
      version: "4.20"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- always_run: false
  as: deploy
  capabilities:
  - intranet
  restrict_network_access: false
  steps:
    cluster_profile: metal-perfscale-selfsched
    env:
      FOREMAN_OS: RHEL 9.6
      MODEL: R630
      NUM_SERVERS: "1"
      STARTING_NODE: "0"
    post:
    - ref: openshift-qe-installer-bm-self-sched-terminate
    pre:
    - ref: openshift-qe-installer-bm-self-sched
    - ref: openshift-qe-installer-bm-ping
    - ref: openshift-qe-installer-bm-prereqs
    - ref: openshift-qe-installer-bm-foreman
    test:
    - ref: openshift-qe-microshift-deploy
zz_generated_metadata:
  branch: main
  org: openshift-eng
  repo: ocp-qe-perfscale-ci
  variant: microshift-metal-selfsched-x86
